#version 450
#extension GL_KHR_vulkan_glsl : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

#include "chunkgen/common.glsl"

void main() {
    uvec3 global_i = gl_GlobalInvocationID.xyz;
    vec3 bp = vec3(global_i) + p.pos.xyz;
    uint tile = load_tile(bp);

    if (length(ivec3(bp) - ivec3(globals.pick_pos.xyz)) < 100)
        tile = BlockID_Air;

    imageStore(output_image, ivec3(global_i), uvec4(tile));
}
